### ISSUE TITLE
Displaylink always loading

### ISSUE THREAD

**Issue by m2Giles** [negativo17/displaylink#2]
For a few months I've noticed that Gnome in a VM will always default to X. After finally having the time to figure out why gdm would say Wayland wasn't enabled I tracked it down to this package.

Previously you would only modprobe the evdi module on demand. Now it is always loaded. The consequence for this is gdm believing that the evdi cards are hardware GPUs. If both a hardware GPU and virtual GPU are detected by gdm, it will disable Wayland support.

Is there a reason why this transitioned to always loading the evdi module and not loading it on demand?

**Comment by scaronni** [comment]
Definitely interesting, I didn't think this could happen. I've replied in the github issue linked above.

Will revert for now.

**Comment by scaronni** [comment]
Packages live in a few minutes.
